<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit107deca29b3757be8754faee3c7bd327
{
    public static $prefixesPsr0 = array (
        'o' => 
        array (
            'ohmy' => 
            array (
                0 => __DIR__ . '/..' . '/ohmy/auth/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit107deca29b3757be8754faee3c7bd327::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
